--liquibase formatted sql

--changeset alramz:global-configuration-settings-table

CREATE TABLE IF NOT EXISTS GLOBAL_CONFIGURATION_SETTINGS (
    ID               BIGSERIAL      PRIMARY KEY,
    IDENTIFIER       VARCHAR(255)   NOT NULL,
    IDENTIFIER_TYPE  VARCHAR(255)   NOT NULL,
    IDENTIFIER_TEXT  VARCHAR(500)   NOT NULL,
    STATUS           VARCHAR(20),
    UNIQUE (IDENTIFIER)
);

CREATE INDEX IF NOT EXISTS IDX_GLOBAL_CONFIGURATION_SETTINGS_IDENTIFIER ON GLOBAL_CONFIGURATION_SETTINGS (IDENTIFIER);
CREATE INDEX IF NOT EXISTS IDX_GLOBAL_CONFIGURATION_SETTINGS_IDENTIFIER_TYPE ON GLOBAL_CONFIGURATION_SETTINGS (IDENTIFIER_TYPE);
CREATE INDEX IF NOT EXISTS IDX_GLOBAL_CONFIGURATION_SETTINGS_STATUS ON GLOBAL_CONFIGURATION_SETTINGS (STATUS);

--rollback DROP TABLE IF EXISTS GLOBAL_CONFIGURATION_SETTINGS;
