--liquibase formatted sql

--changeset alramz:reference-data-table

CREATE TABLE IF NOT EXISTS REFERENCE_DATA (
    ID               BIGSERIAL      PRIMARY KEY,
    IDENTIFIER       VARCHAR(255)   NOT NULL,
    IDENTIFIER_TYPE  VARCHAR(255)   NOT NULL,
    IDENTIFIER_TEXT  VARCHAR(500)   NOT NULL,
    STATUS           VARCHAR(20),
    UNIQUE (IDENTIFIER)
);

CREATE INDEX IF NOT EXISTS IDX_REFERENCE_DATA_IDENTIFIER ON REFERENCE_DATA (IDENTIFIER);
CREATE INDEX IF NOT EXISTS IDX_REFERENCE_DATA_IDENTIFIER_TYPE ON REFERENCE_DATA (IDENTIFIER_TYPE);
CREATE INDEX IF NOT EXISTS IDX_REFERENCE_DATA_STATUS ON REFERENCE_DATA (STATUS);

--rollback DROP TABLE IF EXISTS REFERENCE_DATA;
