-- ===================================================================
-- Insert Sample Global Configuration Settings (Demo Data)
-- ===================================================================
-- liquibase formatted sql
-- changeset liquibase:006-insert-global-configuration-settings.sql:1

INSERT INTO GLOBAL_CONFIGURATION_SETTINGS (IDENTIFIER, IDENTIFIER_TYPE, IDENTIFIER_TEXT, STATUS)
VALUES ('COUNTRY_US', 'ISO_CODE', 'United States', 'ACTIVE');

INSERT INTO GLOBAL_CONFIGURATION_SETTINGS (IDENTIFIER, IDENTIFIER_TYPE, IDENTIFIER_TEXT, STATUS)
VALUES ('COUNTRY_GB', 'ISO_CODE', 'United Kingdom', 'ACTIVE');

INSERT INTO GLOBAL_CONFIGURATION_SETTINGS (IDENTIFIER, IDENTIFIER_TYPE, IDENTIFIER_TEXT, STATUS)
VALUES ('COUNTRY_AE', 'ISO_CODE', 'United Arab Emirates', 'ACTIVE');

INSERT INTO GLOBAL_CONFIGURATION_SETTINGS (IDENTIFIER, IDENTIFIER_TYPE, IDENTIFIER_TEXT, STATUS)
VALUES ('CURRENCY_USD', 'CODE', 'US Dollar', 'ACTIVE');

INSERT INTO GLOBAL_CONFIGURATION_SETTINGS (IDENTIFIER, IDENTIFIER_TYPE, IDENTIFIER_TEXT, STATUS)
VALUES ('CURRENCY_AED', 'CODE', 'UAE Dirham', 'ACTIVE');

INSERT INTO GLOBAL_CONFIGURATION_SETTINGS (IDENTIFIER, IDENTIFIER_TYPE, IDENTIFIER_TEXT, STATUS)
VALUES ('STATUS_ACTIVE', 'STATUS', 'Active', 'ACTIVE');

INSERT INTO GLOBAL_CONFIGURATION_SETTINGS (IDENTIFIER, IDENTIFIER_TYPE, IDENTIFIER_TEXT, STATUS)
VALUES ('STATUS_INACTIVE', 'STATUS', 'Inactive', 'ACTIVE');
