--liquibase formatted sql
--changeset gaurav:002-cities-table

CREATE TABLE CITIES (
    CITY_CODE INTEGER NOT NULL,
    COUNTRY_CODE INTEGER,
    REGION_CODE VARCHAR2(20),
    CITY_NAME_ENGLISH VARCHAR2(50),
    CITY_NAME_ARABIC VARCHAR2(50),
    CITY_SH_NA VARCHAR2(50),
    E_SHORT_NAME VARCHAR2(20),
    TEL_CODE VARCHAR2(20),
    ADX_CITY VARCHAR2(50),
    ADX_CITY_CODE VARCHAR2(20),
    ACTIVE VARCHAR2(20),
    CONSTRAINT CITIES_PK PRIMARY KEY (CITY_CODE)
);
