--liquibase formatted sql
--changeset gaurav:002-banks-table

CREATE TABLE BANKS (
    ID SERIAL PRIMARY KEY,
    BANK_CODE VARCHAR(20),
    BANK_NAME_ENGLISH VARCHAR(500),
    BANK_NAME_ARABIC VARCHAR(500),
    FIT_CODE VARCHAR(20),
    ADX_CODE VARCHAR(20),
    ACTIVE INTEGER NOT NULL,
    SORT INTEGER NOT NULL,
    IBAN_BANK_CODE VARCHAR(20),
    SWIFT_CODE VARCHAR(11)
);

CREATE UNIQUE INDEX BANKS_UK1 ON BANKS(SORT);

--changeset gaurav:003-banks-data

Insert into BANKS (ID,BANK_CODE,BANK_NAME_ENGLISH,BANK_NAME_ARABIC,FIT_CODE,ADX_CODE,ACTIVE,SORT,IBAN_BANK_CODE,SWIFT_CODE) values (421,'PIBCPS','Palestine Islamic bank','Palestine Islamic bank',null,'PS008',1,309,null,null);
Insert into BANKS (ID,BANK_CODE,BANK_NAME_ENGLISH,BANK_NAME_ARABIC,FIT_CODE,ADX_CODE,ACTIVE,SORT,IBAN_BANK_CODE,SWIFT_CODE) values (422,'BJORPS','Bank of Jordan PLC','Bank of Jordan PLC',null,'PS009',1,310,null,null);