--liquibase formatted sql
--changeset gaurav:006-cities-table

CREATE TABLE CITIES (
    CITY_CODE INTEGER NOT NULL,
    COUNTRY_CODE INTEGER,
    REGION_CODE VARCHAR(20),
    CITY_NAME_ENGLISH VARCHAR(50),
    CITY_NAME_ARABIC VARCHAR(50),
    CITY_SH_NA VARCHAR(50),
    E_SHORT_NAME VARCHAR(20),
    TEL_CODE VARCHAR(20),
    ADX_CITY VARCHAR(50),
    ADX_CITY_CODE VARCHAR(20),
    ACTIVE VARCHAR(20),
    CONSTRAINT CITIES_PK PRIMARY KEY (CITY_CODE)
);
