-- ===================================================================
-- Reference Data Table Creation
-- ===================================================================
-- liquibase formatted sql
-- changeset liquibase:004-reference-data-table.sql:1

CREATE TABLE IF NOT EXISTS REFERENCE_DATA (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IDENTIFIER VARCHAR(255) NOT NULL UNIQUE,
    IDENTIFIER_TYPE VARCHAR(255) NOT NULL,
    IDENTIFIER_TEXT VARCHAR(500) NOT NULL,
    STATUS VARCHAR(255)
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_identifier ON REFERENCE_DATA(IDENTIFIER);
CREATE INDEX IF NOT EXISTS idx_identifier_type ON REFERENCE_DATA(IDENTIFIER_TYPE);
CREATE INDEX IF NOT EXISTS idx_status ON REFERENCE_DATA(STATUS);
