-- ===================================================================
-- Global Configuration Settings Table Creation
-- ===================================================================
-- liquibase formatted sql
-- changeset liquibase:004-global-configuration-settings-table.sql:1

CREATE TABLE IF NOT EXISTS GLOBAL_CONFIGURATION_SETTINGS (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IDENTIFIER VARCHAR(255) NOT NULL UNIQUE,
    IDENTIFIER_TYPE VARCHAR(255) NOT NULL,
    IDENTIFIER_TEXT VARCHAR(500) NOT NULL,
    STATUS VARCHAR(255)
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_identifier ON GLOBAL_CONFIGURATION_SETTINGS(IDENTIFIER);
CREATE INDEX IF NOT EXISTS idx_identifier_type ON GLOBAL_CONFIGURATION_SETTINGS(IDENTIFIER_TYPE);
CREATE INDEX IF NOT EXISTS idx_status ON GLOBAL_CONFIGURATION_SETTINGS(STATUS);
