package com.alramz.repository;

import com.alramz.model.EmpRelateds;
import com.alramz.model.Csr;
import lombok.Builder;
import lombok.Data;

import java.time.LocalDate;
import java.util.Map;

@Data
@Builder
public class DfmOnboardingRequest {
    private String requestId;
    private String mobileNumber;
    private String emailAddress;
    private String nin;
    private LocalDate eidDateOfBirth;
    private LocalDate eidExpiryDate;
    private String eidFullName;
    private String eidNumber;
    private LocalDate eidIssueDate;
    private String eidPrimaryId;
    private String eidSecondaryId;
    private String eidGender;
    private LocalDate eidResidencyExpiryDate;
    private String eidResidencyNumber;
    private String eidFamilyId;
    private String eidNationality;
    private String eidArabicFullName;
    private String eidAttachmentFront;
    private String eidAttachmentBack;
    private String eidAttachmentType;
    private LocalDate ppDateOfBirth;
    private LocalDate ppExpiryDate;
    private String ppFullName;
    private String ppNumber;
    private String ppNationality;
    private String ppPrimaryId;
    private String ppSecondaryId;
    private String ppGender;
    private String ppAttachment;
    private String ppAttachmentType;
    private String address;
    private String cityName;
    private String motherName;
    private String pobox;
    private String phone;
    private String country;
    private String signatureAttachment;
    private String signatureAttachmentType;
    private String paymentMethod;
    private String paymentAedIban;
    private String paymentUsdIban;
    private String paymentFrnIban;
    private String paymentFrnSwift;
    private String paymentCorIban;
    private String paymentCorSwift;
    private String paymentRouteCode;
    private String portfolioOptions;
    private String employmentStatus;
    private String employerName;
    private String employmentPosition;
    private String employerMarketOrIssuer;
    private String employerMarketOrIssuerCompanies;
    private String relatedToMarketEmployee;
    private java.util.List<EmpRelateds> empRelateds;
    private String sourceOfIncome;
    private String annualIncomeRange;
    private String investmentKnowledgeExtent;
    private String investmentStrategy;
    private String investmentKnowledgeInstruments;
    private String investmentRiskTolerance;
    private String investmentAmount;
    private String investmentKnowledgeInTrading;
    private String investmentKnowledgeSource;
    private String educationLevel;
    private String investmentPreviousKnowledge;
    private String investmentFrequency;
    private String investmentHighRiskAwareness;
    private String investmentNetEquity;
    private String accreditedByAuthority;
    private String accreditedByAuthorityList;
    private String accreditedByAuthorityType;
    private String qualifiedInvestor;
    private Csr csr;
    private String fatcaUsCitizen;
    private String fatcaTin;
    private String backgroundCheck;
    private Map<String, String> kycMatchDetails;
    private String marginTradingNumber;
    private String memberReferenceNumber;
    private String accountStatus;
    private String userCode;
    private String fitNumber;
}
