--liquibase formatted sql
--changeset gaurav:007-banks-table

CREATE TABLE BANKS (
    ID INTEGER NOT NULL,
    BANK_CODE VARCHAR(20),
    BANK_NAME_ENGLISH VARCHAR(500),
    BANK_NAME_ARABIC VARCHAR(500),
    FIT_CODE VARCHAR(20),
    ADX_CODE VARCHAR(20),
    ACTIVE INTEGER NOT NULL,
    SORT INTEGER NOT NULL,
    IBAN_BANK_CODE VARCHAR(20),
    SWIFT_CODE VARCHAR(11),
    CONSTRAINT BANKS_PK PRIMARY KEY (ID)
);
