CREATE DATABASE "alramz-mw-dev-db" OWNER alramzmw;

GRANT ALL PRIVILEGES ON DATABASE "alramz-mw-dev-db" TO alramzmw;

GRANT ALL ON SCHEMA public TO alramzmw;

GRANT ALL ON ALL TABLES IN SCHEMA public TO alramzmw;

GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO alramzmw;

GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO alramzmw;



ALTER DEFAULT PRIVILEGES IN SCHEMA public

GRANT ALL ON TABLES TO alramzmw;



ALTER DEFAULT PRIVILEGES IN SCHEMA public

GRANT ALL ON SEQUENCES TO alramzmw;



ALTER DEFAULT PRIVILEGES IN SCHEMA public

GRANT ALL ON FUNCTIONS TO alramzmw;